on: [push]
name: Haskell Builds
jobs:
  build:
    name: Haskell Build
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    strategy:
      fail-fast: false
      matrix:
        ghc-version:
          - '9.6'
          - '9.8'
          - '9.10'
          - '9.12'
        cabal-version: ['3.14.2.0']
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup
        if: steps.tooling-cache.outputs.cache-hit != 'true'
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      # Generate Plan
      - name: Configure the Build
        run: |
          rm cabal.project.freeze
          cabal configure --enable-tests --disable-optimization
          cabal build --dry-run

      # Restore cache
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}

      # Build deps (for caching)
      - name: Cabal build dependencies
        run: cabal build all --only-dependencies

      # Save dependency cache
      - name: Save cache
        uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      # Cabal build
      - name: Cabal Bulid
        run: |
          cabal build all

      # Cabal tests
      - name: Cabal Test
        run: |
          cabal test all

  build-lower-bounds:
    name: Haskell Build (lower bounds)
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    strategy:
      fail-fast: false
      matrix:
        ghc-version: ['9.6.7']
        cabal-version: ['3.12.1.0']
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup
        if: steps.tooling-cache.outputs.cache-hit != 'true'
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      # Generate Plan
      - name: Configure the Build
        run: |
          (cat << EOF
          packages: .
          constraints:
            aeson == 2.1.2.1,
            base == 4.18.3.0,
            bytestring == 0.11.3.0,
            generics-sop == 0.5.1.3,
            hspec == 2.11.7,
            postgresql-syntax == 0.4.1,
            squeal-postgresql == 0.9.1.3,
            template-haskell == 2.20.0.0,
            text == 1.2.5.0,
            time == 1.9.3,
            uuid == 1.3.15

            -- Extra, for Squeal
            , postgresql-binary == 0.13.1.3
          EOF
          ) > cabal.project
          rm cabal.project.freeze
          cabal configure --enable-tests --disable-optimization
          cabal build --dry-run

      # Restore cache
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}

      # Build deps (for caching)
      - name: Cabal build dependencies
        run: cabal build all --only-dependencies

      # Save dependency cache
      - name: Save cache
        uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      # Cabal Build
      - name: Cabal Bulid
        run: cabal build all

      # Cabal Test
      - name: Cabal Test
        run: cabal test all
